/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbastecimentoRouteImport } from './routes/abastecimento'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as GanhosDiariosRouteImport } from './routes/ganhos-diarios'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RepassesRouteImport } from './routes/repasses'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastecimentoRoute = AbastecimentoRouteImport.update({
  id: '/abastecimento',
  path: '/abastecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const GanhosDiariosRoute = GanhosDiariosRouteImport.update({
  id: '/ganhos-diarios',
  path: '/ganhos-diarios',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const RepassesRoute = RepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abastecimento': typeof AbastecimentoRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/ganhos-diarios': typeof GanhosDiariosRoute
  '/lancamentos': typeof LancamentosRoute
  '/manutencao': typeof ManutencaoRoute
  '/perfil': typeof PerfilRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorio': typeof RelatorioRoute
  '/repasses': typeof RepassesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abastecimento': typeof AbastecimentoRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/ganhos-diarios': typeof GanhosDiariosRoute
  '/lancamentos': typeof LancamentosRoute
  '/manutencao': typeof ManutencaoRoute
  '/perfil': typeof PerfilRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorio': typeof RelatorioRoute
  '/repasses': typeof RepassesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abastecimento': typeof AbastecimentoRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/ganhos-diarios': typeof GanhosDiariosRoute
  '/lancamentos': typeof LancamentosRoute
  '/manutencao': typeof ManutencaoRoute
  '/perfil': typeof PerfilRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorio': typeof RelatorioRoute
  '/repasses': typeof RepassesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abastecimento'
    | '/admin'
    | '/auth'
    | '/configuracoes'
    | '/despesas'
    | '/ganhos-diarios'
    | '/lancamentos'
    | '/manutencao'
    | '/perfil'
    | '/redefinir-senha'
    | '/relatorio'
    | '/repasses'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abastecimento'
    | '/auth'
    | '/configuracoes'
    | '/despesas'
    | '/ganhos-diarios'
    | '/lancamentos'
    | '/manutencao'
    | '/perfil'
    | '/redefinir-senha'
    | '/relatorio'
    | '/repasses'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/abastecimento'
    | '/admin'
    | '/auth'
    | '/configuracoes'
    | '/despesas'
    | '/ganhos-diarios'
    | '/lancamentos'
    | '/manutencao'
    | '/perfil'
    | '/redefinir-senha'
    | '/relatorio'
    | '/repasses'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbastecimentoRoute: typeof AbastecimentoRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DespesasRoute: typeof DespesasRoute
  GanhosDiariosRoute: typeof GanhosDiariosRoute
  LancamentosRoute: typeof LancamentosRoute
  ManutencaoRoute: typeof ManutencaoRoute
  PerfilRoute: typeof PerfilRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RelatorioRoute: typeof RelatorioRoute
  RepassesRoute: typeof RepassesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abastecimento': {
      id: '/abastecimento'
      path: '/abastecimento'
      fullPath: '/abastecimento'
      preLoaderRoute: typeof AbastecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ganhos-diarios': {
      id: '/ganhos-diarios'
      path: '/ganhos-diarios'
      fullPath: '/ganhos-diarios'
      preLoaderRoute: typeof GanhosDiariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repasses': {
      id: '/repasses'
      path: '/repasses'
      fullPath: '/repasses'
      preLoaderRoute: typeof RepassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbastecimentoRoute: AbastecimentoRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DespesasRoute: DespesasRoute,
  GanhosDiariosRoute: GanhosDiariosRoute,
  LancamentosRoute: LancamentosRoute,
  ManutencaoRoute: ManutencaoRoute,
  PerfilRoute: PerfilRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RelatorioRoute: RelatorioRoute,
  RepassesRoute: RepassesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
