/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbastecimentoRouteImport } from './routes/abastecimento'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConfirmadoRouteImport } from './routes/confirmado'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RepassesRouteImport } from './routes/repasses'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TourRouteImport } from './routes/tour'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastecimentoRoute = AbastecimentoRouteImport.update({
  id: '/abastecimento',
  path: '/abastecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmadoRoute = ConfirmadoRouteImport.update({
  id: '/confirmado',
  path: '/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const RepassesRoute = RepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abastecimento': typeof AbastecimentoRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora': typeof CalculadoraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/confirmado': typeof ConfirmadoRoute
  '/contato': typeof ContatoRoute
  '/despesas': typeof DespesasRoute
  '/inicio': typeof InicioRoute
  '/lancamentos': typeof LancamentosRoute
  '/manutencao': typeof ManutencaoRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorio': typeof RelatorioRoute
  '/repasses': typeof RepassesRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/tour': typeof TourRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abastecimento': typeof AbastecimentoRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora': typeof CalculadoraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/confirmado': typeof ConfirmadoRoute
  '/contato': typeof ContatoRoute
  '/despesas': typeof DespesasRoute
  '/inicio': typeof InicioRoute
  '/lancamentos': typeof LancamentosRoute
  '/manutencao': typeof ManutencaoRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorio': typeof RelatorioRoute
  '/repasses': typeof RepassesRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/tour': typeof TourRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abastecimento': typeof AbastecimentoRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora': typeof CalculadoraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/confirmado': typeof ConfirmadoRoute
  '/contato': typeof ContatoRoute
  '/despesas': typeof DespesasRoute
  '/inicio': typeof InicioRoute
  '/lancamentos': typeof LancamentosRoute
  '/manutencao': typeof ManutencaoRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorio': typeof RelatorioRoute
  '/repasses': typeof RepassesRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/tour': typeof TourRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abastecimento'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/calculadora'
    | '/configuracoes'
    | '/confirmado'
    | '/contato'
    | '/despesas'
    | '/inicio'
    | '/lancamentos'
    | '/manutencao'
    | '/perfil'
    | '/premium'
    | '/privacidade'
    | '/redefinir-senha'
    | '/relatorio'
    | '/repasses'
    | '/sobre'
    | '/termos'
    | '/tour'
    | '/admin/assinaturas'
    | '/admin/usuarios'
    | '/blog/$slug'
    | '/admin/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abastecimento'
    | '/auth'
    | '/blog'
    | '/calculadora'
    | '/configuracoes'
    | '/confirmado'
    | '/contato'
    | '/despesas'
    | '/inicio'
    | '/lancamentos'
    | '/manutencao'
    | '/perfil'
    | '/premium'
    | '/privacidade'
    | '/redefinir-senha'
    | '/relatorio'
    | '/repasses'
    | '/sobre'
    | '/termos'
    | '/tour'
    | '/admin/assinaturas'
    | '/admin/usuarios'
    | '/blog/$slug'
    | '/admin'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/abastecimento'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/calculadora'
    | '/configuracoes'
    | '/confirmado'
    | '/contato'
    | '/despesas'
    | '/inicio'
    | '/lancamentos'
    | '/manutencao'
    | '/perfil'
    | '/premium'
    | '/privacidade'
    | '/redefinir-senha'
    | '/relatorio'
    | '/repasses'
    | '/sobre'
    | '/termos'
    | '/tour'
    | '/admin/assinaturas'
    | '/admin/usuarios'
    | '/blog/$slug'
    | '/admin/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbastecimentoRoute: typeof AbastecimentoRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculadoraRoute: typeof CalculadoraRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConfirmadoRoute: typeof ConfirmadoRoute
  ContatoRoute: typeof ContatoRoute
  DespesasRoute: typeof DespesasRoute
  InicioRoute: typeof InicioRoute
  LancamentosRoute: typeof LancamentosRoute
  ManutencaoRoute: typeof ManutencaoRoute
  PerfilRoute: typeof PerfilRoute
  PremiumRoute: typeof PremiumRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RelatorioRoute: typeof RelatorioRoute
  RepassesRoute: typeof RepassesRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  TourRoute: typeof TourRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abastecimento': {
      id: '/abastecimento'
      path: '/abastecimento'
      fullPath: '/abastecimento'
      preLoaderRoute: typeof AbastecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmado': {
      id: '/confirmado'
      path: '/confirmado'
      fullPath: '/confirmado'
      preLoaderRoute: typeof ConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repasses': {
      id: '/repasses'
      path: '/repasses'
      fullPath: '/repasses'
      preLoaderRoute: typeof RepassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbastecimentoRoute: AbastecimentoRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculadoraRoute: CalculadoraRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConfirmadoRoute: ConfirmadoRoute,
  ContatoRoute: ContatoRoute,
  DespesasRoute: DespesasRoute,
  InicioRoute: InicioRoute,
  LancamentosRoute: LancamentosRoute,
  ManutencaoRoute: ManutencaoRoute,
  PerfilRoute: PerfilRoute,
  PremiumRoute: PremiumRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RelatorioRoute: RelatorioRoute,
  RepassesRoute: RepassesRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  TourRoute: TourRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
