/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbastecimentoRouteImport } from './routes/abastecimento'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as GanhosDiariosRouteImport } from './routes/ganhos-diarios'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RepassesRouteImport } from './routes/repasses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastecimentoRoute = AbastecimentoRouteImport.update({
  id: '/abastecimento',
  path: '/abastecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const GanhosDiariosRoute = GanhosDiariosRouteImport.update({
  id: '/ganhos-diarios',
  path: '/ganhos-diarios',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const RepassesRoute = RepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abastecimento': typeof AbastecimentoRoute
  '/despesas': typeof DespesasRoute
  '/ganhos-diarios': typeof GanhosDiariosRoute
  '/lancamentos': typeof LancamentosRoute
  '/manutencao': typeof ManutencaoRoute
  '/relatorio': typeof RelatorioRoute
  '/repasses': typeof RepassesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abastecimento': typeof AbastecimentoRoute
  '/despesas': typeof DespesasRoute
  '/ganhos-diarios': typeof GanhosDiariosRoute
  '/lancamentos': typeof LancamentosRoute
  '/manutencao': typeof ManutencaoRoute
  '/relatorio': typeof RelatorioRoute
  '/repasses': typeof RepassesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abastecimento': typeof AbastecimentoRoute
  '/despesas': typeof DespesasRoute
  '/ganhos-diarios': typeof GanhosDiariosRoute
  '/lancamentos': typeof LancamentosRoute
  '/manutencao': typeof ManutencaoRoute
  '/relatorio': typeof RelatorioRoute
  '/repasses': typeof RepassesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abastecimento'
    | '/despesas'
    | '/ganhos-diarios'
    | '/lancamentos'
    | '/manutencao'
    | '/relatorio'
    | '/repasses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abastecimento'
    | '/despesas'
    | '/ganhos-diarios'
    | '/lancamentos'
    | '/manutencao'
    | '/relatorio'
    | '/repasses'
  id:
    | '__root__'
    | '/'
    | '/abastecimento'
    | '/despesas'
    | '/ganhos-diarios'
    | '/lancamentos'
    | '/manutencao'
    | '/relatorio'
    | '/repasses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbastecimentoRoute: typeof AbastecimentoRoute
  DespesasRoute: typeof DespesasRoute
  GanhosDiariosRoute: typeof GanhosDiariosRoute
  LancamentosRoute: typeof LancamentosRoute
  ManutencaoRoute: typeof ManutencaoRoute
  RelatorioRoute: typeof RelatorioRoute
  RepassesRoute: typeof RepassesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abastecimento': {
      id: '/abastecimento'
      path: '/abastecimento'
      fullPath: '/abastecimento'
      preLoaderRoute: typeof AbastecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ganhos-diarios': {
      id: '/ganhos-diarios'
      path: '/ganhos-diarios'
      fullPath: '/ganhos-diarios'
      preLoaderRoute: typeof GanhosDiariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repasses': {
      id: '/repasses'
      path: '/repasses'
      fullPath: '/repasses'
      preLoaderRoute: typeof RepassesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbastecimentoRoute: AbastecimentoRoute,
  DespesasRoute: DespesasRoute,
  GanhosDiariosRoute: GanhosDiariosRoute,
  LancamentosRoute: LancamentosRoute,
  ManutencaoRoute: ManutencaoRoute,
  RelatorioRoute: RelatorioRoute,
  RepassesRoute: RepassesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
