name: Build Android AAB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Conceder permissão de execução para o Gradle
      run: chmod +x gradlew

    - name: Gerar AAB de Release
      run: ./gradlew bundleRelease

    - name: Salvar o arquivo AAB nos Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: app/build/outputs/bundle/release/app-release.aab
